### ISSUE TITLE
usage of -webkit-fill-available causes fill-available warning

### ISSUE THREAD

**Issue by UncleClapton** [postcss/autoprefixer#1050]
Hi, I am currently receiving the warning `Replace fill-available to stretch, because spec had been changed` when building my css bundle. I've traced the cause down to the css file of a dependency which uses the styles:

```
    max-height: -webkit-fill-available;
    max-height: -moz-available;
    max-height: stretch;
```

I believe that autoprefixer is erroneously throwing a warning for the use of `-webpkit-fill-available`. Removing this line resolves the issue, however since this is a dependency's css, it's not really a solution. Any ideas?

**Comment by ai** [comment]
I will try to fix it 👍

**Comment by ai** [comment]
Done 89627f3

**Comment by ai** [comment]
Released in 8.5.1. Thanks for report.

**Comment by Komald** [comment]
Hi @ai 
I am still getting the warnings for `-webkit-fill-available`.
Here is the piece of css
 ```
 height: stretch;
  height: -webkit-fill-available;
  height: -moz-available; 
```

**Comment by ai** [comment]
@Komald 

1. Check Autoprefixer version by `npm ls | grep autoprefixer`
2. Remove `-moz-available` and `-webkit-fill-available` from your code (not to fix issue, just because it is best practice)

**Comment by Komald** [comment]
I have just updated the module, version is 8.6.5 as per the changelog.

**Comment by ai** [comment]
@Komald tested and didn’t get any warnings. Can you create a test project?

**Comment by Komald** [comment]
Ok. I will create and share one.

**Comment by Komald** [comment]
I tried but not able to create a pen which will reproduce the issue. Will update again if succeed.

**Comment by ai** [comment]
Maybe you accidentally had old version of Autoprefixer? Or some other dependency used old version.

**Comment by Komald** [comment]
Yeah, the dependencies could be the issue. Thanks for your help @ai
