### ISSUE TITLE
TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by MarkShakespeare** [postcss/autoprefixer#1252]
Since the release of `9.6.2` we've been unable to build our projects using autofixer as we get the error `TypeError: Cannot read property 'startsWith' of undefined`. 

Seems like it was caused by this change:
https://github.com/postcss/autoprefixer/commit/8768ce4c00e8dd261bb25a07b450e99ac02ef43e#diff-1ea033eede7961e81fac67f7cf52fd51R82

**Comment by ai** [comment]
Show full stacktrace and CSS input

**Comment by MarkShakespeare** [comment]
While building in storybook:

```ERROR in ./scopes/verticals/nova.report-comparison/src/components/nova-table/nova-table.css (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??postcss!./scopes/verticals/nova.report-comparison/src/components/nova-table/nova-table.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot read property 'startsWith' of undefined
    at /Users/markshakespeare/workspace/js-modules.verticals/scopes/verticals/nova.report-comparison/src/components/nova-table/nova-table.css:9:5
    at /Users/markshakespeare/workspace/js-modules.verticals/node_modules/autoprefixer/lib/processor.js:84:41
    at Array.some (<anonymous>)
    at Rule.some (/Users/markshakespeare/workspace/js-modules.verticals/node_modules/postcss/lib/container.js:701:23)
    at insideGrid (/Users/markshakespeare/workspace/js-modules.verticals/node_modules/autoprefixer/lib/processor.js:82:26)
    at /Users/markshakespeare/workspace/js-modules.verticals/node_modules/autoprefixer/lib/processor.js:136:61
    at /Users/markshakespeare/workspace/js-modules.verticals/node_modules/postcss/lib/container.js:190:18
    at /Users/markshakespeare/workspace/js-modules.verticals/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/Users/markshakespeare/workspace/js-modules.verticals/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/Users/markshakespeare/workspace/js-modules.verticals/node_modules/postcss/lib/container.js:131:17)
    at /Users/markshakespeare/workspace/js-modules.verticals/node_modules/postcss/lib/container.js:148:24
    at Root.each (/Users/markshakespeare/workspace/js-modules.verticals/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/Users/markshakespeare/workspace/js-modules.verticals/node_modules/postcss/lib/container.js:131:17)
    at Root.walkDecls (/Users/markshakespeare/workspace/js-modules.verticals/node_modules/postcss/lib/container.js:188:19)
    at Processor.add (/Users/markshakespeare/workspace/js-modules.verticals/node_modules/autoprefixer/lib/processor.js:97:9)
    at plugin (/Users/markshakespeare/workspace/js-modules.verticals/node_modules/autoprefixer/lib/autoprefixer.js:123:26)
    at supportedFeatures.reduce.then (/Users/markshakespeare/workspace/js-modules.verticals/node_modules/postcss-preset-env/index.js:443:157)
 @ ./scopes/verticals/nova.report-comparison/src/components/nova-table/nova-table.css 2:14-175 21:1-42:3 22:19-180
 @ ./scopes/verticals/nova.report-comparison/src/components/nova-table/nova-table.js
 @ ./scopes/verticals/nova.report-comparison/src/components/nova-table/index.js
 @ ./scopes/verticals/nova.report-comparison/src/components/report-connections/report-connections.js
 @ ./scopes/verticals/nova.report-comparison/src/components/report-connections/index.js
 @ ./scopes/verticals/nova.report-comparison/src/report-comparison-page.js
 @ ./scopes/verticals/nova.report-comparison/src/index.js
 @ ./scopes/verticals/nova.report-comparison/storybook/index.stories.js
 @ ./scopes sync \.stories\.js$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js (webpack)-hot-middleware/client.js?reload=true&quiet=true```

**Comment by ai** [comment]
Fixed 3151e61

**Comment by ai** [comment]
Released in 9.6.3

**Comment by MarkShakespeare** [comment]
> Released in 9.6.3

@ai i've bumped to `9.6.3` and am still getting the same errors

**Comment by ai** [comment]
Oops b07ba02

**Comment by ai** [comment]
Released in 9.6.4

**Comment by MarkShakespeare** [comment]
fixed 👍
